# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "drk/centos-7"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

#  config.vm.network "forwarded_port", guest: 5432,  host: 5432, host_ip: "127.0.0.1"  # postgres  
  config.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1" # forward default rails port
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1" # forward default nginx port
  config.vm.network "forwarded_port", guest: 4040,  host: 4040     # ngrok interface


  config.vm.network "public_network", ip: "192.168.1.10", bridge: "en1: Wi-Fi (AirPort)"

#  config.vm.synced_folder "../server/dist", "/box", type: 'rsync'

  config.vbguest.auto_update = false
  config.vm.synced_folder "../", "/project", type: "virtualbox", disabled: false # set up shared folder
  config.vm.synced_folder "../server/", "/box"

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update
    curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
    source ~/.bashrc
    nvm install 18
    nvm install 16
    nvm install 14
    nvm install 12
  SHELL
end
